name: Example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    
jobs:
  statsig-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Evaluate
        id: statsig
        uses: ./
        with:
          sdk-key: ${{ secrets.SDK_KEY }}
          user: '{ "userID": "test123", "email": "test123@statsig.com" }'
          log-exposures: 'false'
          gates: | 
            always_pass
            always_fail
            statsig_email
          configs: |
            statsig_pets
      - name: Print output
        run: |
          echo ${{ steps.statsig.outputs.gate_always_pass }}
          echo ${{ steps.statsig.outputs.gate_always_fail }}
          echo ${{ steps.statsig.outputs.gate_statsig_email }}
          echo '${{ toJSON(steps.statsig.outputs.config_statsig_pets_roles) }}'